project:
  type: book
  output-dir: _book
  
book:
  title: "Titre général"
  author: "Deux doux dingues"
  description: | 
    TBA
  #cover-image: images/cover.png
  site-url: https://tutorials.thecoatlessprofessor.com/quarto-book-template
  repo-url: https://github.com/coatless-tutorials/quarto-book-template
  repo-branch: main
  repo-actions: [edit]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - part: my-first-book.qmd
      chapters: 
        - hello-world.qmd
        - hello-world2.qmd
    - part: my-first-book2.qmd
      chapters: 
        - hello-world.qmd
        - hello-world2.qmd
  appendices:
    - appendix-notes.qmd
    
format:
  html: 
    theme: cosmo
    code-link: true
